export const EXERCISES_IT = [
  "Squat",
  "Squat bulgaro",
  "Squat sumo",
  "Front squat",
  "Panca piana",
  "Panca inclinata",
  "Panca declinata",
  "Panca con manubri",
  "Stacco da terra",
  "Stacco rumeno",
  "Stacco sumo",
  "Stacco gambe tese",
  "Trazioni",
  "Trazioni presa larga",
  "Trazioni presa stretta",
  "Chin up",
  "Piegamenti",
  "Push up",
  "Dip parallele",
  "Rematore bilanciere",
  "Rematore manubrio",
  "Rematore T-bar",
  "Rematore cavi",
  "Lento avanti",
  "Military press",
  "Arnold press",
  "Push press",
  "Leg press",
  "Leg extension",
  "Leg curl",
  "Leg curl in piedi",
  "Affondi",
  "Affondi con manubri",
  "Affondi bulgari",
  "Affondi camminati",
  "Croci panca",
  "Croci manubri",
  "Croci ai cavi",
  "Cable fly",
  "Curl bilanciere",
  "Curl manubri",
  "Curl martello",
  "Curl concentrato",
  "Curl cavi",
  "French press",
  "Pushdown cavi",
  "Estensioni tricipiti",
  "Kickback tricipiti",
  "Face pull",
  "Alzate laterali",
  "Alzate frontali",
  "Alzate posteriori",
  "Shrugs",
  "Tirate al mento",
  "Crunch",
  "Crunch inverso",
  "Plank",
  "Plank laterale",
  "Bicycle crunch",
  "Russian twist",
  "Dead bug",
  "Mountain climbers",
  "Hanging leg raise",
  "Pull up",
  "Lat machine",
  "Lat machine presa larga",
  "Lat machine presa stretta",
  "Pulley basso",
  "Pulley alto",
  "Fly petto",
  "Pec deck",
  "Hip thrust",
  "Hip thrust bilanciere",
  "Glute bridge",
  "Donkey kicks",
  "Clamshell",
  "Fire hydrant",
  "Calf raise",
  "Calf seduto",
  "Box jump",
  "Burpees",
  "Kettlebell swing",
  "Thruster",
  "Clean",
  "Snatch",
  "Power clean",
  "Overhead squat",
  "Goblet squat",
  "Farmer walk",
  "Plank to pike",
  "Ab wheel rollout",
  "Landmine press",
  "Landmine row",
  "Good morning",
  "Hyperextension",
  "Nordic curl",
  "Pistol squat",
  "Panca stretta",
  "Dip petto",
  "Dip tricipiti",
];
